
server:
  tomcat:
    max-http-header-size: 16384
    
  port: 9000
  

spring:
 application:
  name: apiGateway
  
 cloud:
  gateway:
   routes:  
    
    - id: AppUtil
      uri: lb://APPUTIL
      predicates:
       - Path=/apputil/**
      filters:
       - AuthenticationFilter
    
    - id: authentication
      uri: lb://AUTHENTICATION
      predicates:
       - Path=/auth/**
      filters:
       - AuthenticationFilter
       
    - id: catalog
      uri: lb://CATALOG
      predicates:
       - Path=/catalog/**
      filters:
       - AuthenticationFilter
    
    - id: orders
      uri: lb://ORDERS
      predicates:
       - Path=/orders/**
      filters:
       - AuthenticationFilter
    
    - id: payments
      uri: lb://PAYMENTS
      predicates:
       - Path=/payments/**
      filters:
       - AuthenticationFilter
       
    - id: store
      uri: lb://STORE
      predicates:
       - Path=/store/** 
      filters:
       - AuthenticationFilter
       
    - id: UserCart
      uri: lb://USERCART
      predicates:
       - Path=/usercart/**  
      filters:
       - AuthenticationFilter 
    
                  
  discovery:
   locator:
    enabled: true
    lower-case-service-id: true
    
eureka:
 instance:
  preferIpAddress: true
 client:
  fetch-registry: true
  register-with-eureka: true
  serviceUrl:
   defaultZone: http://localhost:3786/eureka/
   
management:
 endpoints:
  web:
   exposure:
    include: "*"
 endpoint:
  shutdown:
   enabled: true
    
 info:
  env:
   enabled: true

endpoints:
 shutdown:
  enabled: true
    
info:
 app:
  name: "eatprotein"
  description: "eatprotein application"
  version: "1.0.0"
  
#springdoc:
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
#  api-docs:
#    path: /v3/api-docs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

    
       