server:
  port: 8081

spring:
 data:
  redis:
   host: localhost
   port: 6379
 application:
  name: SportsCenter
  
 datasource:
  url: jdbc:mysql://localhost:3306/sports_center?reconnect=true&zeroDateTimeBehavior=convertToNull&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
  username: root
  password: Bobby@2002
  driver-class-name: com.mysql.cj.jdbc.Driver
  
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.MySQLDialect

 